name: logic

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "README.md"
jobs:
  alt-build:
    runs-on: ubuntu-latest
    steps:
      - name: exit 1
      - run: exit 1
  telegram-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message on failure
        if: ${{ jobs.alt-build.result }} == 'failure'
      - name: Send Telegram message on success
        if: ${{ jobs.alt-build.result }} == 'success'
